language: python
python:
  - "3.7.2"

before_script:
  - pip install -r requirements.txt

branches:
  only:
    - staging

env: DJANGO_SETTINGS_MODULE="oc_projet_8.settings.travis"

services:
  - postgresql

script:
  - ./manage.py test