language: python
python:
  - "3.6.2"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'create database test;' -U postgres
  - psql -c "CREATE USER besevic WITH PASSWORD 'hWfY7Uv82k7L9f2Sr._.';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE travis_ci_test TO besevic;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE test TO besevic;" -U postgres
  - pip install -r requirements.txt

branches:
  only:
    - staging

env: DJANGO_SETTINGS_MODULE="oc_projet_8.settings.travis"

services:
  - postgresql

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test